language: rust
os: osx
rust:
  - stable
  - beta
  - nightly
script:
  - (cd lib/bootstrap_rs && cargo build)
  - (cd lib/bootstrap_rs && cargo build --example window)
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
